### ISSUE TITLE
Host paradigm as github page

### ISSUE THREAD

**Issue by DominiqueMakowski** [JingxiongXu/JRA#1]
FYI, if you have your index.html at the base of the repo or in a folder called "docs", you can then enable a GitHub page in the settings of your repo, which will effectively host it online. It will be useful for me to try your paradigm without having to send over the files locally ;)

**Comment by JingxiongXu** [comment]
Thank you for your feedback, I made some changes so that it is possible to run the experiment simply by clicking the link.
